name: Feature Request
description: Suggest an idea or enhancement for Query Store Reports
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out the form below to help us understand your request.

  - type: textarea
    id: problem-statement
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe the problem you're trying to solve.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've also thought about...

  - type: dropdown
    id: feature-category
    attributes:
      label: Feature Category
      description: What category does this feature fall into?
      options:
        - New Report Type
        - Existing Report Enhancement
        - UI/UX Improvement
        - Performance Improvement
        - Authentication/Connection
        - Query Plan Viewer
        - Data Export/Formatting
        - Configuration/Settings
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Nice to have
        - Would be helpful
        - Important
        - Critical
    validations:
      required: false

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe a specific scenario or use case where this feature would be beneficial.
      placeholder: When I'm working on..., this feature would help me...

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, screenshots, or examples from other tools that demonstrate the feature.
      placeholder: Paste or drag images here, or describe what you envision...

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, related issues, or references about the feature request here.
      placeholder: Any additional information...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing this feature?
      options:
        - label: I would be willing to contribute this feature with guidance
        - label: I can help test this feature when implemented
